Ship to
hostgator/Business-CyberSource pull request #14
Opened 2017-03-03 17:52 UTC by bvoskr

2017-03-06 14:35 UTC, elderling requested changes
I don't see the value added by the ['SetOnce'] trait, but if we're going to use it here then we need explain why some attributes have it and others do not. Some attributes have aliases and others do not but the aliases don't match the .xsd and the documentation in the class doesn't justify the need for them. If the aliases are justified for some reason I don't understand, the attributes with aliases don't have predicates for those aliases.

2017-03-06 15:56 UTC, bvoskr commented
As for aliases, I simply saw them as a way to simplify request initialization for the developer. E.g., allow to use 'building' instead of 'buildingNumber', 'zip' instead of 'postal_code', 'phone' instead of 'phone_number' etc. Didn't put any more meaning to this. Since the only usage for alias was request initialization, I didn't care for predicates for aliases, too.

As for SetOnce trait, there are two topics which I want to separate:
1. 'ro' vs 'rw' attributes
2. Applying SetOnce trait to 'rw' attributes.

### 'ro' vs 'rw' attributes. 
As I see it (which is often wrong), 'rw' attributes are the ones that allowed to be added/modified in existing request for the convenience purposes (like adding building number, or phone number, etc. ) They do not redefine the delivery recipient, and do not affect funds calculation.
The attribute may be non-required, but ‘ro’ - e.g. first/last name, as it identifies the recipient.
The tests now are setting attributes during ShipTo initialization, and will probably pass even if I make all attributes 'ro'. But I’m quite sure division of attributes into 'ro' and 'rw' must remain.

### Applying SetOnce trait to 'rw' attributes.
Whether to apply SetOnce trait to the 'rw' attributes, I really do not have the clear answer. I was following pattern from “BillTo” field, which was applying SetOnce trait to all ‘rw’ fields. I'm ready to remove the trait.

2017-03-08 15:39 UTC, elderling requested changes

2017-03-08 15:54 UTC, bvoskr commented on lib/MooseX/Types/CyberSource.pm
> +subtype ShippingMethod, as _VarcharTen,
I actually thought about this. But SO API specs mentions two separate requirements for shipping method. One is, that max field length is 10, and another, listing possible supported values (none of them reaching max field length).
Enum would only cover supported values requirement. Current implementation covers both.

2017-03-08 16:05 UTC, bvoskr commented on t/shipto.t
> +# commenting code below till understand how MooseX works with undefined attributes
Will remove.

2017-03-08 16:18 UTC, bvoskr commented on t/shipto-exceptions.t
> +
I'm missing the coverage context. It is either about sandbox being able to swallow all the fields, or about the integrity of the ShipTo object. 

- If former, I agree, and add all possible fields. It is, though, related to xt/ tests, not to t/shipto-exceptions.t

- If latter, t/shipto-exceptions.t seem to cover all the fail cases. t/shipto.t must be extended with missing fields.

2017-03-09 13:49 UTC, elderling approved these changes

2017-03-09 13:52 UTC, merged